#Se a침adi칩 todas las credenciales por defecto debido a que se usar치 la misma
#base de datos para desarrollo, test y producci칩n.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
